version: '3.8'
services:
  cs336:
    build:
      context: .
    ports: 
      - 8080:8080
    environment:
      - DB_URL=jdbc:mysql://db/cs336

  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=cs336
      - MYSQL_PASSWORD=cs336
      - MYSQL_DATABASE=cs336

volumes:
  data:
